import os
from datetime import datetime


class ReportGenerator:
    def __init__(self, output_dir="results"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_html_report(self, results, charts, filename="report.html"):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        filepath = os.path.join(self.output_dir, filename)

        html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Agents Pipeline Report</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 40px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background-color: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
        }}
        .status-success {{
            color: #27ae60;
            font-weight: bold;
            font-size: 1.2em;
        }}
        .status-error {{
            color: #e74c3c;
            font-weight: bold;
            font-size: 1.2em;
        }}
        .metrics {{
            background-color: #ecf0f1;
            padding: 20px;
            border-radius: 5px;
            margin: 20px 0;
        }}
        .metric-item {{
            padding: 8px;
            margin: 5px 0;
            background-color: white;
            border-left: 4px solid #3498db;
            padding-left: 15px;
        }}
        .chart {{
            margin: 20px 0;
            text-align: center;
        }}
        .chart img {{
            max-width: 100%;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 10px;
            background-color: white;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #7f8c8d;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🤖 AI Agents Pipeline Report</h1>
        <p><strong>Generated:</strong> {timestamp}</p>

        <h2>📊 Status</h2>
        <p class="status-{results['status']}">{results['status'].upper()}</p>

        <h2>📈 Metrics</h2>
        <div class="metrics">
"""

        for key, value in results['metrics'].items():
            html_content += f'            <div class="metric-item"><strong>{key}:</strong> {value}</div>\n'

        html_content += """        </div>

        <h2>📊 Visualizations</h2>
"""

        for chart_name, chart_path in charts.items():
            rel_path = os.path.relpath(chart_path, self.output_dir)
            html_content += f"""        <div class="chart">
            <h3>{chart_name}</h3>
            <img src="{rel_path}" alt="{chart_name}">
        </div>
"""

        html_content += """        <div class="footer">
            <p>Generated by AI Agents Data Science Automation System</p>
            <p>© 2025 - Orchestrator Agent</p>
        </div>
    </div>
</body>
</html>
"""

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)

        return filepath